### ISSUE TITLE
Datum der StuRa Sitzung mit ausgeben

### ISSUE THREAD

**Issue by lu-kors** [Ref-IT/ProtokollCleaner#2]
Für die Finanzbeschlüsse die aktuell im JSON-Format 

{
 "token":"Beschlussnr"
}

ausgegeben werden, soll zusätzlich die Information des Datums der Sitzung mit ausgegeben werden. 

Gewünschtes Neues Format: 
{
"YYY-MM-DD":
     {
      "token1": "beschluss1",
      "token2": "beschluss2"
  } ,
"Datum2": 
{
      "token3": "beschluss3",
      "token4": "beschluss4"
  }

**Comment by Cherrg** [comment]
an welcher Stelle war denn diese API?
Finanzbeschlüsse werden mit in der normalen Beschlussliste geführt und können gefiltert werden.
Ansonsten werden die Beschlüsse parallel noch in eine Datenbank gestopft, wodurch der Abruf aller Finanzbeschlüsse nur noch ein SQLQuery darstellt.
Wird nach Datum Gruppiert, und JSON Codiert fällt das gewünschte Format raus
