### ISSUE TITLE
Documentation schreiben

### ISSUE THREAD

**Issue by targetingsnake** [Ref-IT/ProtokollCleaner#6]

**Comment by Cherrg** [comment]
Falls wer Spaß dran hat, kann er das gerne noch seperat dokumentieren...
Für die PreAlpha Version gab es eine Doku, welche komplett überarbeitet werden müsste.

Der Großteil der Funktionen und Klassen ist mit PHP Doc commentiert. Bei Bedarf kann man das noch rausrendern und mit ins Git stopfen...
