### ISSUE TITLE
ProtokollCleaner Ansatz

### ISSUE THREAD

**Issue by michael-dev** [Ref-IT/ProtokollCleaner#8]
In main.php sehe ich derzeit nix, was Protokolle bereinigt.
Ich halte das auch für keine gute Idee.
Schreibe dafür am Besten ein DokuWiki Plugin, welches das Speichern von veröffentlichten Protokollen mit internem Bereich verhindert.

**Comment by lu-kors** [comment]
Kann man mit der XML API auch schreiben? Warum nicht das verwenden? Sonst geht der Vorteil der Automatisierung verloren

**Comment by lu-kors** [comment]
Falls das Gegenargument kaputte Syntax sein sollte könnte man ja durchaus das erst bei schon beschlossen Protokollen machen, dann muss beim abstimmen halt auf die korrekte Verwendung des flags geachtet werden

**Comment by targetingsnake** [comment]
@michael-dev in der main.php in Zeile 131 ff wird das Protokoll bereinigt. wenn dies im BSP. nicht funktioniert, so muss ich nochmal schaun.

**Comment by michael-dev** [comment]
Ok es wird geschrieben. Ja mit XMLRPC kann man auch schreiben, sonst könnte SGIS nix ins Dokuwiki tun (andere Domain).

Zur Namensgebund: dass die Methode "getAllFiles" letztlich Dateien kopiert, halte ich für sehr unglückliche Namensgebung. Mache eine Methode die beispw. listAllPages heißt, und eine andere, die deren Ausgabe verwendet, um neue Seiten zu erstellen.

**Comment by targetingsnake** [comment]
eigentlich heißt die aufgerufene Methode Copy(), aber die getAllFiles methode müsste man mal zur Mainmethode umbennen.

**Comment by targetingsnake** [comment]
vgl Protokoll Ref IT 2017-11-16
